version: "3.7"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./api:/api']
  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile.dev
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celery-queue:/queue']
  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile.dev
    ports:
     - "5555:5555"
    command:  ['celery', 'flower', '-A', 'tasks']
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./celery-queue:/queue']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  client:
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - web
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  node-modules: