FROM python:3.9-alpine

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 5001
ENV DEBUG true

COPY . /api
WORKDIR /api

RUN pip install -U setuptools pip
RUN pip install -r requirements.txt

EXPOSE 5001

# RUN python manage.py db init
# RUN python manage.py db migrate
# CMD ["python", "manage.py", "db", "init"]


RUN python manage.py

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5001"]
